## Pipelines: chaining pre-processors and estimators

In [ ]:
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split

from sklearn.preprocessing import StandardScaler # TODO: what is it?
from sklearn.compose import ColumnTransformer # TODO: what is it?

from sklearn.pipeline import Pipeline
from sklearn.base import BaseEstimator, TransformerMixin # TODO: what is it?
from sklearn.metrics import mean_squared_error, r2_score

from sklearn.ensemble import RandomForestRegressor

import numpy as np
import joblib
import pandas as pd

In [7]:
data = fetch_california_housing(as_frame=True)

In [14]:
df = data.frame.copy()

In [17]:
df.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422

In [ ]:
X = df.drop("MedHouseVal", axis=1) # X columns are features, i.e. 
X

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25
...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24

In [20]:
y = df["MedHouseVal"]
y

0        4.526
1        3.585
2        3.521
3        3.413
4        3.422
         ...
20635    0.781
20636    0.771
20637    0.923
20638    0.847
20639    0.894
Name: MedHouseVal, Length: 20640, dtype: float64

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [22]:
#create own transformer THIS IS WHAT I NEED TO UNDERSTAND

# Preprocessing stage
class InteractionFeatures(BaseEstimator, TransformerMixin):

    def __init__(self):
        pass

    def fit(self, X, y=None):
        return self

    def transform(self, X):

        X_new = X.copy()
        X_new["Rooms_per_Adult"] = X_new["AveRooms"] / X_new["AveOccup"]

        X_new["Bedrooms_per_Room"] = X_new["AveBedrms"] / X_new["AveRooms"]

        return X_new

In [23]:
numeric_features = X_train.columns.to_list()
numeric_features

['MedInc',
 'HouseAge',
 'AveRooms',
 'AveBedrms',
 'Population',
 'AveOccup',
 'Latitude',
 'Longitude']

In [26]:
preprocessor = Pipeline(

    steps = [

        ("interactions", InteractionFeatures()),
        ("scaler", StandardScaler()),

    ]

)

In [27]:
# Assemble everything: preprocessor + RandomForestRegressor as pipeline

model = Pipeline(
    [
        ("preprocessing", preprocessor),
        ("regressor", RandomForestRegressor())

    ]

)

In [28]:
model.fit(X_train, y_train)

Pipeline(steps=[('preprocessing',
                 Pipeline(steps=[('interactions', InteractionFeatures()),
                                 ('scaler', StandardScaler())])),
                ('regressor', RandomForestRegressor())])

In [29]:
model.predict(X_test)

array([3.4622609, 1.58823  , 0.89925  , ..., 3.4752715, 1.77706  ,
       2.41176  ], shape=(4128,))

In [30]:
mean_squared_error(y_test, model.predict(X_test))

0.26573330677871426

In [ ]:
#save entire pipeline

joblib.dump(model, "california_pipeline_model.joblib")
joblib.dump(model, "california_pipeline_model.pkl")

# TODO: not sure how to use

['california_pipeline_model.pkl']